[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name         tail
    Path         /var/lib/docker/containers/*/*-json.log
    Parser       docker
    Tag          docker.*
    Refresh_Interval 10
    Mem_Buf_Limit 5MB
    Skip_Long_Lines On
    DB           /var/log/fluentbit/docker.db

[FILTER]
    Name         modify
    Match        docker.*
    Add          folder_id b1gl2o95u528n9i3k1ea

[OUTPUT]
    Name         http
    Match        docker.*
    Host         ingester.logging.yandexcloud.net
    Port         443
    URI          /logging/v1/write
    Format       json_lines
    TLS          On
    Header       Authorization Bearer ${YC_IAM_TOKEN}
    Retry_Limit  3
